
image:
  file: .gitpod.dockerfile
tasks:
 - init: . ${GITPOD_REPO_ROOT}/.theia/init_tasks.sh    
#vscode:
  #extensions:
  #  - ms-python.python@2019.8.30787
  # - formulahendry.auto-close-tag@0.5.6
  # - mkaufman.HTMLHint@0.6.0
  #  - eventyret.bootstrap-4-cdn-snippet@1.6.0
  #  - esbenp.prettier-vscode@4.3.0
  #  - kevinglasson.cornflakes-linter@0.4.0


vscode:
  extensions:
    - formulahendry.auto-close-tag